version: "3.7"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - '5601:5601'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch-container
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    networks:
      - default
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
  db_mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  db_postgres:
    image: postgres:9.6.15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  rails:
    build: "."
    container_name: rails-container
    command: /bin/bash
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/docker
    depends_on:
      - db_mysql
      - db_postgres
      - elasticsearch
